### ISSUE TITLE
Image uploads seem to be failing for events, groups

### ISSUE THREAD

**Issue by skylineproject** [jamescmartinez/coffee#215] opened 2019-06-18 17:13 UTC
Hi all!

I'm Brandon, and Jaim added me as an organizer of [MSP Coffee](https://coffeecoffeecoffee.coffee/msp-coffee). We've been looking at adding events and filling out the rest of our profile, but it looks like image uploads are failing.

I've tried uploading JPEGs and PNGs of various sizes, but they all seem to fail. For example, this is what is returned as the image url for our most recent event: [this image](https://coffeecoffeecoffee.coffee/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWt5TnpNd1lXSXhOQzFtTnpobExUUTJObUV0WVRZeFlTMWlOV1ExWWpJd01XRTNZek1HT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--25f76d779a50eac4f3e8865a737bf652c6cb5241/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9VWTI5dFltbHVaVjl2Y0hScGIyNXpld1k2QzNKbGMybDZaVWtpRHpFd09EQjRNVGt5TUQ0R09nWkZWQT09IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--0f0d6b4931d30bc6d6933fa3807785841b09eebc/IMG_4621.jpg) 

I'll clone the repo and dig in momentarily to see if I can figure out what's going on locally, but in the meantime, if there's something clear about this I'm missing or can be fixed without a code change, let me know.

Thanks!

**Comment by jamescmartinez** [comment] 2019-06-18 17:19
@skylineproject Thanks for creating this. I see what you're talking about in the server logs. I've got a few to debug this right now; I'll post back in a bit.

**Comment by skylineproject** [comment] 2019-06-18 17:38
Awesome, thanks! fwiw, this is the image used for that upload: 
![IMG_4621](https://user-images.githubusercontent.com/5009403/59706399-02eab880-91c6-11e9-91d9-6527e03bb48f.jpg)

**Comment by jamescmartinez** [comment] 2019-06-18 17:47
Weird. Looks like the event image works but the group image doesn't. https://coffeecoffeecoffee.coffee/msp-coffee

I've tried reuploading and am getting a combination of weird errors from our image service, Cloudinary.

Hypothesis: https://support.cloudinary.com/hc/en-us/articles/202520452-I-m-getting-a-404-or-other-40x-erros-for-my-transformed-image-while-other-versions-of-that-image-work

**Comment by jamescmartinez** [comment] 2019-06-18 17:51
**Event**

https://coffeecoffeecoffee.coffee/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWt5TnpNd1lXSXhOQzFtTnpobExUUTJObUV0WVRZeFlTMWlOV1ExWWpJd01XRTNZek1HT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--25f76d779a50eac4f3e8865a737bf652c6cb5241/IMG_4621.jpg

-> 

https://api.cloudinary.com/v1_1/coffee/image/download?api_key=738997312699765&attachment=false&expires_at=1560879645&format=jpg&public_id=hn04ku0d7rv5b709wounvjkufozv&signature=ee9e7cfa77b56c098fa3785abad4ce62ccf4dcb6&timestamp=1560879345&type=upload

**Group**

https://coffeecoffeecoffee.coffee/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWxrTWpBeE1EYzNaUzA0WVdRd0xUUTFOR1V0WWpjeE1pMDJNV0V4TkROaU1qVXdNVFlHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--5dcfd92e36fc93bb1a326658bf1dd783ac04e896/pexels-photo-1251175.jpeg

->

https://api.cloudinary.com/v1_1/coffee/raw/download?api_key=738997312699765&attachment=false&expires_at=1560880291&format=jpeg&public_id=87aa1s99ql7osqm51tb3dw027l9i.jpeg&signature=51fa8bc9448ecfb5f509f67f7812a7d00675d71f&timestamp=1560879991&type=upload

**Comment by jamescmartinez** [comment] 2019-06-18 17:52
I have to hop off, can't continue right now, but I'll monitor to see if it's the caching issue. If not I'll need to do some deeper digging.

**Comment by skylineproject** [comment] 2019-06-18 17:52
Right on, thanks so much, @jamescmartinez!

**Comment by jamescmartinez** [comment] 2019-06-18 20:57
@skylineproject There's an image now. Did you do anything? https://coffeecoffeecoffee.coffee/

**Comment by skylineproject** [comment] 2019-06-18 21:47
@jamescmartinez I think Jaim might have re-uploaded a different image at some point this afternoon :)

**Comment by jamescmartinez** [comment] 2019-06-18 21:53
In that case, I'm going to close this since the image works and I can't reproduce to debug. I'll continue to watch for this happening and if you see it happen again please reopen so I can debug more.

**Closed by jamescmartinez** 2019-06-18 21:53 UTC
